// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelegramHelper.Infrastructure;

#nullable disable

namespace TelegramHelper.Infrastructure.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20250927155959_Migration2")]
    partial class Migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelegramHelper.Abstractions.Models.CurrentDynamicFolderFilterModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FilterType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filter_type");

                    b.Property<long>("FolderId")
                        .HasColumnType("bigint")
                        .HasColumnName("folder_id");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("current_dynamic_folder_filters", (string)null);
                });

            modelBuilder.Entity("TelegramHelper.Abstractions.Models.CurrentFolderModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("folder_name");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon_name");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<int>("TelegramFolderId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_folder_id");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "TelegramFolderId")
                        .IsUnique();

                    b.ToTable("folder", (string)null);
                });

            modelBuilder.Entity("TelegramHelper.Abstractions.Models.CurrentStaticFolderFilterModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<long>("FolderId")
                        .HasColumnType("bigint")
                        .HasColumnName("folder_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("current_static_folder_filters", (string)null);
                });

            modelBuilder.Entity("TelegramHelper.Abstractions.Models.DynamicFolderFilterModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("FilterType")
                        .HasColumnType("integer")
                        .HasColumnName("filter_type");

                    b.Property<long>("FolderId")
                        .HasColumnType("bigint")
                        .HasColumnName("folder_id");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("dynamic_folder_filter", (string)null);
                });

            modelBuilder.Entity("TelegramHelper.Abstractions.Models.FolderModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("folder_name");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon_name");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("TelegramHelper.Abstractions.Models.OwnerModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("owner", (string)null);
                });

            modelBuilder.Entity("TelegramHelper.Abstractions.Models.StaticFolderFilterModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<long>("FolderId")
                        .HasColumnType("bigint")
                        .HasColumnName("folder_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("static_folder_filters", (string)null);
                });

            modelBuilder.Entity("TelegramHelper.Abstractions.Models.CurrentDynamicFolderFilterModel", b =>
                {
                    b.HasOne("TelegramHelper.Abstractions.Models.CurrentFolderModel", "Folder")
                        .WithMany("DynamicFilters")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("TelegramHelper.Abstractions.Models.CurrentFolderModel", b =>
                {
                    b.HasOne("TelegramHelper.Abstractions.Models.OwnerModel", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TelegramHelper.Abstractions.Models.CurrentStaticFolderFilterModel", b =>
                {
                    b.HasOne("TelegramHelper.Abstractions.Models.CurrentFolderModel", "Folder")
                        .WithMany("StaticFilters")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("TelegramHelper.Abstractions.Models.DynamicFolderFilterModel", b =>
                {
                    b.HasOne("TelegramHelper.Abstractions.Models.FolderModel", "Folder")
                        .WithMany("DynamicFilters")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("TelegramHelper.Abstractions.Models.FolderModel", b =>
                {
                    b.HasOne("TelegramHelper.Abstractions.Models.OwnerModel", "Owner")
                        .WithMany("Folders")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TelegramHelper.Abstractions.Models.StaticFolderFilterModel", b =>
                {
                    b.HasOne("TelegramHelper.Abstractions.Models.FolderModel", "Folder")
                        .WithMany("StaticFilters")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("TelegramHelper.Abstractions.Models.CurrentFolderModel", b =>
                {
                    b.Navigation("DynamicFilters");

                    b.Navigation("StaticFilters");
                });

            modelBuilder.Entity("TelegramHelper.Abstractions.Models.FolderModel", b =>
                {
                    b.Navigation("DynamicFilters");

                    b.Navigation("StaticFilters");
                });

            modelBuilder.Entity("TelegramHelper.Abstractions.Models.OwnerModel", b =>
                {
                    b.Navigation("Folders");
                });
#pragma warning restore 612, 618
        }
    }
}
